import React, { useState } from "react";
import { Box, Heading, Text, Input, Button, VStack, Textarea, useToast } from "@chakra-ui/react";
import { FaSearch } from "react-icons/fa";

const Index = () => {
  const [topic, setTopic] = useState("");
  const [blogPost, setBlogPost] = useState("");
  const toast = useToast();

  const handleGeneratePost = () => {
    if (topic.trim() === "") {
      toast({
        title: "Please enter a topic",
        status: "warning",
        duration: 3000,
        isClosable: true,
      });
      return;
    }

    // TODO: Integrate with AI backend to generate blog post based on the topic
    const generatedPost = `This is a sample blog post generated by the AI for the topic: ${topic}. The actual implementation would involve making an API call to the backend AI service to generate a comprehensive, SEO-friendly blog post based on the provided topic.`;

    setBlogPost(generatedPost);
  };

  return (
    <Box bg="gray.100" minH="100vh" py={8}>
      <Box maxW="3xl" mx="auto" bg="white" borderRadius="md" p={8} boxShadow="lg">
        <Heading as="h1" size="xl" mb={6} color="blue.600">
          UseMe4SEO
        </Heading>
        <Text fontSize="xl" mb={8}>
          Automatically generate SEO-friendly blog posts to enhance your website's visibility and ranking on search engines.
        </Text>
        <VStack spacing={6} align="stretch">
          <Input placeholder="Enter a topic or keywords" size="lg" value={topic} onChange={(e) => setTopic(e.target.value)} />
          <Button colorScheme="blue" size="lg" rightIcon={<FaSearch />} onClick={handleGeneratePost}>
            Generate Blog Post
          </Button>
          {blogPost && (
            <Box mt={8}>
              <Heading as="h2" size="lg" mb={4}>
                Generated Blog Post:
              </Heading>
              <Textarea value={blogPost} isReadOnly size="lg" minH="300px" borderColor="gray.300" />
            </Box>
          )}
        </VStack>
      </Box>
    </Box>
  );
};

export default Index;
